version: '3'
services:
  faktory:
    image: contribsys/faktory
    volumes:
      - ./faktory/data:/var/lib/faktory
    ports:
      - 7420:7420
  hubot:
    build:
      context: ./hubot
    volumes:
      - ./hubot:/hubot
    environment:
      FAKTORY_URL: faktory:7419
    depends_on:
      - faktory
  worker:
    build:
      context: ./worker
    volumes:
      - ./worker:/worker
    environment:
      FAKTORY_PROVIDER: FAKTORY_URL
      FAKTORY_URL: tcp://faktory:7419
    depends_on:
      - faktory
